name: 'Publish Docker'
author: 'John Son'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  repository:
    description: 'Repository on registry'
    required: true
  registry:
    description: 'Registry hostname'
    required: false
  tag:
    description: 'Image tag'
    required: false

outputs:
  tag:
    description: 'Tagged image'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.repository }}
    - ${{ inputs.registry }}
    - ${{ inputs.tag }}
